# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-gradio-streamlit
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - opencv
  - pip:
    - huggingface-hub
    - tensorflow
    - keras
    - matplotlib
    - numpy
    - gradio
    - streamlit
    - streamlit-image-comparison
    - requests